version: "3"
services:

  ktn-wallet-iapi:
    image: ktn-wallet-iapi
    build: .
    restart: always
    volumes:
      - ./:/webapps
    ports:
      - 6008:5005
    networks:
      - base-network
    command: gunicorn --bind 0.0.0.0:5005 --workers=1 main:app --log-level=debug -c conf/gunicorn.py --timeout 0

  ktn-wallet-dapp:
    image: ktn-wallet-iapi
    build: .
    restart: always
    volumes:
      - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q katana-dapp-wallet-iapi-queue -l INFO -c 4

  ktn-wallet-tx-queue:
    image: ktn-wallet-tx-queue
    build: .
    restart: always
    volumes:
      - ./:/webapps
    networks:
      - base-network
    command: celery --app wallet worker -Q ktn-wallet-tx-queue -l INFO -c 4
  
  ktn-wallet-receipt-tx-queue:
    image: ktn-wallet-iapi
    build: .
    restart: always
    volumes:
      - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q wallet-receipt-tx-queue -l INFO -c 4

  ktn-wallet-pending-tx-queue:
    image:  ktn-wallet-iapi
    build: .
    restart: always
    volumes:
      - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-wallet-pending-tx-queue -l INFO -c 4
  
  ktn-wallet-point-queue:
    image: ktn-wallet-iapi
    build: .
    restart: always
    volumes:
      - ./:/webapps
    networks:
      - base-network
    command: celery --app worker worker -Q ktn-point-queue -l INFO -c 4

networks:
  base-network:
    external: true
